use super::state::{AgendaProjection, CalendarRange, SidebarSection};
use crate::agenda::{AgendaCommand, BuiltinQuery, FileId, TaskKey};
use jiff::civil::{Date, Time};
use std::sync::Arc;

#[derive(Clone, Debug)]
pub(crate) enum UiIntent {
    ToggleSidebarSection(SidebarSection),
    ShowSourceContextMenu(FileId, gpui::Point<gpui::Pixels>),
    CloseSourceContextMenu,
    SelectNavigation(&'static str, BuiltinQuery),
    SetProjection(AgendaProjection),
    SetCalendarRange(CalendarRange),
    ShiftCalendar(i32),
    CalendarToday,
    ToggleAllDay,
    ToggleDayGroup(Option<Date>),
    NavigateBack,
    NavigateForward,
    MoveOccurrence(usize, Date, Option<Time>),
    ResizeOccurrence(usize, Date, Time),
    SelectRow(usize),
    OpenSource(TaskKey),
    SetSearch(String),
    SetTag(Option<Arc<str>>),
    SetSource(Option<FileId>),
    Apply(TaskKey, AgendaCommand),
    CloseInspector,
    CloseOverlay,
    RequestDelete,
    CancelDelete,
    ConfirmDelete(TaskKey),
    OpenCapture,
    SetCaptureTemplate(crate::agenda::CaptureTemplate),
    SubmitCapture,
    StartInboxOrganize,
    InboxSkip,
    InboxFinish,
    ExitInboxOrganize,
    SelectProject(usize),
    OpenProjectSource,
    OpenRefile(TaskKey),
    RefileNext(i32),
    SubmitRefile,
    ResumeRecovery,
    CleanupRecovery,
    ToggleClock(TaskKey),
    SelectSavedView(usize),
    RequestTodoTransition(TaskKey, Arc<str>),
    ResolveRepeat(crate::agenda::RepeatCompletionAction),
}
